# Generated by Django 3.0.6 on 2020-05-24 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='post',
            new_name='post_that_i_wrote_a_comment',
        ),
    ]
